server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: rental
          uri: http://localhost:8081
          predicates:
            - Path=/rentals/**
        - id: pay
          uri: http://localhost:8082
          predicates:
            - Path=/pays/** 
        - id: book
          uri: http://localhost:8083
          predicates:
            - Path=/books/**


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: rental
          uri: http://rental:8080
          predicates:
            - Path=/rentals/**
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/pays/** 
        - id: book
          uri: http://book:8080
          predicates:
            - Path=/books/**

server:
  port: 8080
